### ISSUE TITLE
Negotiation question

### ISSUE THREAD

**Issue by Scratch-net** [go-noisetls/noise_socket_spec#1]
Hi @trevp, I'd like to discuss negotiation & versions here. I like the idea of several handshake messages but have some trouble with understanding the versioning, espesially this one:

> Suppose the client wants to offer three new ciphers (version 1-3) but reuse the version 0 DH. The client can send version indicators for 1-3, each followed by a zero-length message, reusing the version 0 message's ephemeral public value.

Could you please explain the idea a bit more?

Also, does it mean that you want all the negotiation options (ciphersuites also) are to be done via version numbers?

Noise_XX_25519_AESGCM_SHA256 will be 0, Noise_XX_25519_ChaChaPoly_BLAKE2s wil be 1 and so on? Looks like 1 byte will be over soon enough)

**Comment by trevp** [comment]
Might be better to keep this discussion on the mailing list, where more people will see it, e.g. on this thread: https://moderncrypto.org/mail-archive/noise/2017/000866.html

But quick responses.  First, imagine if version 0 = 25519_AESGCM_SHA256, version 1 = 25519_ChaChaPoly_BLAKE2s,  like your example.  They both use 25519, so you don't want to repeat the ephemeral public key in the initial message, you just want to send 1 ephemeral public key that can be used with either.  E.g:

2 bytes length = 38
  1 byte version = 0
  2 bytes length =   32
  <25519 public key "e">
  1 byte version = 1
  2 bytes length = 0

Second, yes, I was thinking *all* negotiation would be done by numbers.  But there wouldn't be a global mapping, each NoiseSocket user would assign their own version numbers. Creating a global mapping means we need some coordinated registry of numbers, which is a hassle.  

Noise was designed to use strings as global names.  So if we wanted to avoid users numbering their own protocols we'd have to use strings, instead of version numbers.  That might be worth proposing, if you wanted to mention it on mailing list?

**Comment by Scratch-net** [comment]
Thanks for the explanation, much clearer now. Will continue on the mailing list)
